regularSymbols: ^|{}[]

spring:
  profiles:
    active: "dev"
---
spring:
  profiles: dev
  -datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  -jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
server:
  tomcat:
    uri-encoding: utf-8